name: CI Docs

on:
  pull_request:
    types: [milestoned, opened, reopened, synchronize]
    paths:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - docs/**
      - .vscode/**
      - .gitignore
      - renovate.json
      - .release-please-config.json
      - release-please-config.json
      - CODEOWNERS
      - LICENSE

jobs:
  check-only-docs-changes:
    runs-on: ubuntu-latest
    outputs:
      only_docs_changed: ${{ step.set_output.outputs.only_docs_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for non-docs changes
        id: docs_check
        uses: ./.github/actions/check-non-docs-changes
        with:
          base_ref: ${{ github.base_ref }}

      - name: Set outputs
        id: set_output
        run: echo "only_docs_changed=${{ steps.docs_check.outputs.non_docs_changed == 'false' }}" >> $GITHUB_ENV

  docs-only:
    needs: check-only-docs-changes
    if: needs.check-only-docs-changes.outputs.only_docs_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Lint Check (Simulated)
        run: echo "Simulating lint-check job - Success!"

      - name: Check Paths (Simulated)
        run: echo "Simulating check-paths job - Success!"

      - name: Package Test (Simulated)
        run: echo "Simulating run-package-test job - Success!"

      - name: Compliance Test (Simulated)
        run: echo "Simulating evaluate-package-compliance job - Success!"

      - name: Slim Dev Test (Simulated)
        run: echo "Documentation-only change detected; marking test successful."
