name: CI Docs Shim

# Trigger this workflow on pull requests that affect documentation or certain config files.
on:
  pull_request:
    paths:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - docs/**
      - .vscode/**
      - .gitignore
      - renovate.json
      - .release-please-config.json
      - release-please-config.json
      - CODEOWNERS
      - LICENSE

# Define placeholder jobs to simulate the full workflow.
jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Check (Simulated)
        run: echo "Simulating lint-check job - Success!"

  check-paths:
    needs: lint-check
    runs-on: ubuntu-latest
    steps:
      - name: Check Paths (Simulated)
        run: echo "Simulating check-paths job - Success!"

  run-package-test:
    needs: check-paths
    runs-on: ubuntu-latest
    steps:
      - name: Run Package Test (Simulated)
        run: echo "Simulating run-package-test job - Success!"

  evaluate-package-compliance:
    needs: run-package-test
    runs-on: ubuntu-latest
    steps:
      - name: Evaluate Package Compliance (Simulated)
        run: echo "Simulating evaluate-package-compliance job - Success!"

  # slim-dev-test.yaml
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Shim for test
        run: |
          echo "Documentation-only change detected; marking test successful."
