name: CI Docs

on:
  pull_request:
    types: [milestoned, opened, reopened, synchronize]
    paths:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - docs/**
      - .vscode/**
      - .gitignore
      - renovate.json
      - .release-please-config.json
      - release-please-config.json
      - CODEOWNERS
      - LICENSE

jobs:
  check-only-docs-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check for non-doc changes
        id: check_non_docs
        run: |
          # Check if any non-doc/config files were changed
          non_doc_changes=$(git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }} -- \
          ':!**.md' ':!**.jpg' ':!**.png' ':!**.gif' ':!**.svg' ':!docs/**' \
          ':!.vscode/**' ':!.gitignore' ':!renovate.json' ':!.release-please-config.json' \
          ':!release-please-config.json' ':!CODEOWNERS' ':!LICENSE')

          if [ -n "$non_doc_changes" ]; then
            echo "Non-doc/config files were changed:"
            echo "$non_doc_changes"
            exit 1
          else
            echo "Only doc/config files were changed."
          fi

  docs:
    needs: check-only-docs-changes
    if: needs.check-only-docs-changes.outputs.only_docs_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Lint Check(Simulated)
        run: echo "Simulating lint-check job - Success!"

      - name: Check Paths(Simulated)
        run: echo "Simulating check-paths job - Success!"

      - name: Package Test(Simulated)
        run: echo "Simulating run-package-test job - Success!"

      - name: Compliance Test(Simulated)
        run: echo "Simulating evaluate-package-compliance job - Success!"

      - name: Slim Dev Test(Simulated)
        run: echo "Documentation-only change detected; marking test successful."
