name: Slim Dev

on:
  pull_request:
    types: [milestoned, opened, reopened, synchronize]
    paths:
      - src/pepr/*
      - src/keycloak/*
      - src/istio/*
      - src/prometheus-stack/*
      - packages/slim-dev/*
      - bundles/k3d-slim-dev/*
      - .github/workflows/slim-dev*

permissions:
  id-token: write
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash -e -o pipefail {0}

concurrency:
  group: test-slim-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-only-non-docs-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check for non-docs changes
        id: docs_check
        uses: ./.github/actions/check-non-docs-changes
        with:
          base_ref: ${{ github.base_ref }}
      - name: Set outputs
        id: set_output
        run: echo "run_slim_dev=${{ steps.docs_check.outputs.non_docs_changed }}" >> $GITHUB_ENV

  test:
    needs: check-only-non-docs-changes
    if: env.run_slim_dev == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Environment setup
        uses: ./.github/actions/setup
      - name: Deploy Slim Dev Bundle
        run: uds run slim-dev --no-progress
      - name: Debug Output
        if: ${{ always() }}
        uses: ./.github/actions/debug-output
      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
        with:
          suffix: -slim-dev
